sensors:
- name: top_kinect
  type: kinect
  source: /amigo/top_kinect/rgbd
  frame_id: /amigo/top_kinect/openni_rgb_optical_frame
  visualize: 0
  voxel_size: 0.02
  max_range: 2.0
  clearing_padding_fraction: 0.05
  normal_k_search: 15
  association_modules:
  - type: PointNormal
    parameters:
        association_correspondence_distance: 0.3
        position_weight: 2.0
        normal_weight: 1.0
        render_width: 320
        render_max_range: 2.2
        render_voxel_size: 0.02
        normal_k_search: 15
        visualize: 0
  - type: PolygonHeight
    parameters:
        max_range: 2.0
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0
  segmentation_modules:
  - type: EuclideanClustering
    parameters:
        tolerance: 0.035
        min_cluster_size: 20
        visualize: 0

# -----------------------------------------------------------------------------------------------------------------------------

visualize: 1
world_name: robotics_testlabs

# -----------------------------------------------------------------------------------------------------------------------------

perception:
    fit_shapes: 1
    model_list: all_models.yml
    modules:

    - lib: libsize_matcher.so
      parameters:
          size_diff_threshold: 0.8    # size similarity threshold between learned models and the detected object
          small_size_treshold: 0.5    # objects smaller than this (height+witdth in meters) are considered small
          medium_size_treshold: 0.7   # objects between this and the small size (height+witdth in meters) are considered medium

    - lib: libed_odu_finder.so
      parameters:
          database_path: /database    # location of database (ed_object_models/configs/odu_finder + <this path>)
          debug_mode: 0               # activate debug mode for extra output

    - lib: libcolor_matcher.so
      parameters:
          debug_mode: 0                     # activate debug mode for extra output
          debug_folder: /tmp/color_matcher/ # folder for debug output images
          color_table: /color_names.txt     # location of database (ed_object_models/configs/color_matcher + <this path>)

    - lib: libhuman_contour_matcher.so
      parameters:
          debug_mode: 0             # activate debug mode for extra output
          max_template_err: 15      # maximum error for an object to be considered human (0 is perfect match)            
          max_match_iterations: 30  # maximum number of iterations for the template matching
          dt_line_width: 1          # line width used to generate the Distance Transform map
          dt_border_size: 20        # border size used to generate the Distance Transform map
          dt_slices_num: 7          # number of slices to split the Distance Transform map to find best starting point
          debug_folder: /tmp/human_classifier/                                    # folder for debug output images
          head_template_front_path: /head_templates/template_front_4_trimmed.png  # template for frontal head template matching
          head_template_left_path: /head_templates/left_close.png                 # template for left head template matching
          head_template_right_path: /head_templates/right_close.png               # template for right head template matching

    - lib: libface_detector.so
      parameters:
          debug_mode: 0                         # activate debug mode for extra output
          debug_folder: /tmp/face_detector/     # folder for debug output images
          cascade_front_files_path: /cascade_classifiers/haarcascade_frontalface_alt_tree.xml # cascade classifier for frontal face detection
          cascade_profile_front_path: /cascade_classifiers/haarcascade_profileface.xml        # cascade classifier for profile face detection
          classifier_front_scale_factor: 1.2    # scale factor used in the search for frontal faces
          classifier_front_min_neighbours: 3    # minimum number of neighbour detections to consider a valid frontal detection
          classifier_profile_scale_factor: 1.2  # scale factor used in the search for profile faces
          classif_profile_min_neighbours: 3     # minimum number of neighbour detections to consider a valid profile detection

    - lib: libface_recognition_ed.so
      parameters:
        debug_mode: 0                     # activate debug mode for extra output
        save_learned_faces: 0             # automatically save faces learned (boolean)
        saved_faces_dir: /faces_learned/  # location of saved faces (<HOME FODLER> + <this path>)
        use_Eigen: 0                      # enable Eingen Faces recognition (boolean)
        use_Fisher: 1                     # enable Fisher Faces recognition (boolean)
        use_LBPH: 1                       # enable LBPH Faces recognition (boolean) 
        use_histogram: 1                  # enable color matching using histograms (boolean)
        enable_learning_service: 1        # enable learning service (boolean). Topic '/face_recognition/learn <PERSON_NAME>'
        eigen_treshold: 3000              # Eingen Faces error threshold (less is better)
        fisher_treshold: 800              # Fisher Faces error threshold (less is better)
        lbph_treshold: 45                 # LBPH Faces error threshold (less is better) 
        recognition_treshold: 0.95        # final recognition threshold (less is better)
        face_target_size: 150             # size of faces used in the recognition process (square, in pixels) 
        left_eye_vert_offset: 0.35        # offset of the left eye from the top of the image
        left_eye_horiz_offset: 0.25       # offset of the left eye from the left of the image
        max_faces_learn: 10               # number of samples to be learned for each new face

    - lib: libtype_aggregator.so
      parameters:
        classification_threshold: 0.5     # final classification threshold

# -----------------------------------------------------------------------------------------------------------------------------

plugins:
- name: gui_server
  lib: libed_gui_server_plugin.so
  parameters:
      robot_name: amigo
#- name: builder
#  lib: libed_builder_plugin.so
- name: obstacle_grid_publisher
  lib: libed_occupancy_grid_publisher_plugin.so
  parameters:
      frequency: 10
      resolution: 0.05
      topic: /ed_map
      frame_id: /map
      sim_time: 1.0
      object_persistence_time: 10
- name: loc_grid_publisher
  lib: libed_occupancy_grid_publisher_plugin.so
  parameters:
      frequency: 1
      resolution: 0.025
      topic: /ed_loc_map
      frame_id: /map
      specifier: localizable
      sim_time: 0.0
- name: tf_publisher
  lib: libed_tf_publisher_plugin.so
  parameters:
      root_frame_id: /map
- name: localization
  lib: libed_localization_plugin.so
  parameters:
      initial_pose_topic: /amigo/initialpose
      num_particles: 500
      initial_pose:
          x: $(env ROBOT_INIT_X)
          y: $(env ROBOT_INIT_Y)
          rz: $(env ROBOT_INIT_PHI)    
      laser_model:
          topic: /amigo/base_front_laser
          num_beams: 100
          z_hit: 0.95
          sigma_hit: 0.2
          z_short: 0.1
          z_max: 0.05
          z_rand: 0.05
          lambda_short: 0.1
          range_max: 10
          min_particle_distance: 0.01
          min_particle_rotation_distance: 0.02
      odom_model:
          map_frame: map
          odom_frame: /amigo/odom
          base_link_frame: /amigo/base_link
          alpha1: 0.05   # rot -> trans + strafe
          alpha2: 0.5    # trans -> rot
          alpha3: 0.5    # trans -> trans
          alpha4: 0.5    # rot -> rot
          alpha5: 0.5    # trans -> strafe
